### ISSUE TITLE
Invalidation threshold not respected

### ISSUE THREAD

**Issue by ashfurrow** [leighmcculloch/middleman-cdn#10]
As of #9, there's a `invalidate_zone_for_many_files` option for Cloudflare that means "if I have more than 50 files to invalidate, I'll just invalidate the zone (to avoid hitting the API rate limit)." The option is supposed to default to true, but wouldn't work until [I added it explicitly](https://github.com/ashfurrow/blog/commit/97002273338b25e4eff5a4dea4b557e5bd34f982).

Failing deploy: https://travis-ci.org/ashfurrow/blog/builds/119957771#L7481
Succeeding deploy (with explicit option): https://travis-ci.org/ashfurrow/blog/builds/120216017#L5992

Please let me know if I can be off assistance debugging.

**Comment by leighmcculloch** [comment]
Fix is released in version `0.1.16`.

**Comment by ashfurrow** [comment]
![](http://f.cl.ly/items/3y0f1W090x1T3k2v2f3r/success_kid.jpg)
