### ISSUE TITLE
CloudFlare cache invalidation is broken

### ISSUE THREAD

**Issue by mkalygin** [leighmcculloch/middleman-cdn#17]
This commit https://github.com/leighmcculloch/middleman-cdn/commit/6ecd16d739f0ac73555c05f776399641b6a967d9 introduced a compatibility issue with CloudFlare gem. The gem's API has been changed and the correct connection call now looks like this (see the gem's [docs](https://github.com/ioquatix/cloudflare#usage)):

```ruby
connection = Cloudflare.connect(key: key, email: email)
```

The specs passed because the old `Cloudflare::connection` method is mocked in rspec.

But in reality the `middleman-cdn` gem is not working at all because of this issue.

**Comment by leighmcculloch** [comment]
Doh! I regret mocking that in a way that we weren't alerted that the function no longer existed. @mkalygin would you be up for opening a PR with the fix?

**Comment by mkalygin** [comment]
@leighmcculloch the implementation of `cloudflare` gem has been changed and I'm not sure how much. 😄I'll take a look at it the next week, but if things are complicated, I'd rather find a way to support previous API.

**Comment by leighmcculloch** [comment]
This fix has been released in v0.3.1.
