### ISSUE TITLE
Config parameter validation error always includes "cloudfront[:base_urls]" rather than actual missing parameter name

### ISSUE THREAD

**Issue by brentsnook** [leighmcculloch/middleman-cdn#19]
https://github.com/leighmcculloch/middleman-cdn/blob/707b9669faadf4eb2614670241c68499baec2762/lib/middleman-cdn/cdns/cloudfront.rb#L27

Should probably parameterise config param name in error message.

**Comment by leighmcculloch** [comment]
@brentsnook Could you provide an example of what you mean? Or if the change is very small could you open a PR demonstrating what you mean?

**Comment by brentsnook** [comment]
Sorry about the brevity - I was confused by this because I had failed to set the `secret_access_key` key but the error was "Error: Configuration key cloudfront[:base_urls] is missing." (even though I had already set that). It looks like a typo - other CDN classes parameterise the key name.

**Comment by leighmcculloch** [comment]
Ahh I understand now, thanks for opening #20.

**Comment by brentsnook** [comment]
I think I also noticed this problem in some of the other CDN classes too
