### ISSUE TITLE
Consider moving from colorize to ansi

### ISSUE THREAD

**Issue by ashfurrow** [leighmcculloch/middleman-cdn#5]
Hi there! 

Fantastic tool – thanks so much for building this! The integration with middleman-s3_sync is _very_ helpful. 

Opening this issue because I saw that this gem depends on colorize, which is [licensed under the GPL](https://github.com/fazibear/colorize#license), not a permissive license like on this project. [middleman-s3_sync had the same issue](https://github.com/fredjean/middleman-s3_sync/issues/88#issuecomment-136012660) and switched to [ansi](https://github.com/rubyworks/ansi). If that sounds cool to you, I'm happy to switch over this awesome tool.

**Comment by leighmcculloch** [comment]
Hi – thanks for the kind words! I'm up for switching to `ansi`. The suggestion and offering to do it is much appreciated, thanks!

**Comment by ashfurrow** [comment]
Alright! I'll send a PR this weekend ☕️
