### ISSUE TITLE
Possible issue with Cloudflare invalidations

### ISSUE THREAD

**Issue by ashfurrow** [leighmcculloch/middleman-cdn#8]
Hey! I was noticing rate limit errors [like this one](https://travis-ci.org/ashfurrow/blog/builds/79126777#L3499) happening a lot. The error only made sense if cloudflare was trying to invalidate _everything_, based on [the error message](https://github.com/leighmcculloch/middleman-cdn/blob/72af7cf713fb4606d8fdad1c39d60db06d9439ca/lib/middleman-cdn/cdns/cloudflare.rb#L40-L49). That's based on the `all` parameter, and I took a look at where the method is called. It looks like `all` is inferred from [this method](https://github.com/leighmcculloch/middleman-cdn/blob/28a6b46e39d4ce9fe898f67d0591a24defd50168/lib/middleman-cdn/commands.rb#L111-L113), which is `true` if you're using the default filter. 

From what I can tell, it looks like `all` is being passed into the `invalidate` function incorrectly set to `true` if the filter applies to all files, but within the `invalidate` function, it's inferred to mean "invalidate all files, not the ones I was given."

Let me know if this makes sense, and if I can provide any more details. I [used this fix](https://github.com/ashfurrow/blog/commit/532a8d6dc586560dc83f48dfc7244d27925ca320), and it [appears to be working](https://travis-ci.org/ashfurrow/blog/builds/79139529#L3492-L3497).

**Comment by leighmcculloch** [comment]
Thanks, yeah this wasn't a clear way of supporting 'all'. I supported it this way originally because most CDNs don't have a 'clear all' function, so I thought to add it to CloudFlare I'd just get it to check if the user was invalidating all the files, then just use that instead.

I think the right way of changing this would be to add a flag to the config that said 'invalidate all' which would ignore the filter, and there'd need to be a note in the README saying it's only supported by CloudFlare.

Let me know if you have thoughts.

**Comment by ashfurrow** [comment]
Hmm, tricky. Didn't realize CloudFlare was unique that way. 

I agree with your idea – an 'invalidate all' config would be awesome. I'm hitting API rate limits pretty hard, so I invalidate "all" if I've [changed > 50 files](https://github.com/ashfurrow/blog/blob/9039a549f33d0d4818475ebe11307750fe4b532a/config.rb#L109-L120). It would be ideal if this new config setting could be changed after the initial plugin activation :cake:

**Comment by leighmcculloch** [comment]
I could make the 'invalidate all' config param a Boolean or a Proc/Lambda. Then you can make the decision at the time it's called.

**Comment by ashfurrow** [comment]
👌

**Comment by ashfurrow** [comment]
Just a follow-up on this – I see there's an [`INVALIDATION_LIMIT` constant set to a thousand](https://github.com/leighmcculloch/middleman-cdn/blob/9a3e55b9d6785a07bad53a0f31268045ba63fa5a/lib/middleman-cdn/cdns/cloudfront.rb#L8). I hit validation errors over a hundred updated files. Is it possible that the constant could be changed, or configured?

**Comment by leighmcculloch** [comment]
We could remove the limit from the code technically. The 1000 limit for CloudFront (not CloudFlare) is imposed by the CDN itself, and then I think now, if you go over that you pay a fee.

**Comment by manuelmeurer** [comment]
Would be great to get the "invalidate all" option for Cloudflare in! :+1:

**Comment by manuelmeurer** [comment]
I am still regularly running into this with Cloudflare, only the first 50 files are invalidated, after that Cloudflare reponds with `error: File purge rate limited.`
Can't we just implement the [fix](https://github.com/ashfurrow/blog/blob/9039a549f33d0d4818475ebe11307750fe4b532a/config.rb#L109-L120) from @ashfurrow and invalidate everything when more than 50 files have changed?
I'd be happy to take a stab at it in a PR.

**Comment by leighmcculloch** [comment]
@manuelmeurer agree I like @ashfurrow's fix, let's do it. Can you open a PR? We should make this feature on by default and but so that it can be turned off in the config. This would be for people where it's would be problematic to clear the zones entire cache, like if that would overwhelm the origin.

**Comment by manuelmeurer** [comment]
Absolutely, makes sense! I'll try to get to it next week! :+1:

**Comment by manuelmeurer** [comment]
Would it be okay to remove the `all` parameter from the `invalidate` methods? As you said, it's only used for Cloudflare right now and I think if we invalidate the entire zone automatically on 50+ changes files, there's no need for it.

**Comment by manuelmeurer** [comment]
It was actually quite straightforward to implement! :smile_cat:

**Comment by leighmcculloch** [comment]
Closing as #9 should resolve this. Reopen and let us know if not!
